QUESTIONS = [
  {"q":"Which part of the human body produces red blood cells?","options":["Liver","Spleen","Bone Marrow","Kidneys"],"answer":2,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Lord of the Rings'?","options":["C.S. Lewis","J.R.R. Tolkien","George R.R. Martin","J.K. Rowling"],"answer":1,"category":"Literature","difficulty":"easy"},
  {"q":"What is the chemical symbol for radium?","options":["R","Ra","Rd","Rm"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most diverse ecosystem?","options":["Brazil","Australia","Indonesia","Madagascar"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the properties and behavior of light called?","options":["Optics","Acoustics","Thermodynamics","Electromagnetism"],"answer":0,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most intense auroras?","options":["Earth","Jupiter","Saturn","Neptune"],"answer":1,"category":"Space","difficulty":"hard"},
  {"q":"What does FTP stand for?","options":["File Transfer Protocol","File Transmission Protocol","File Transport Protocol","File Translation Protocol"],"answer":0,"category":"Technology","difficulty":"medium"},
  {"q":"What is the value of the derivative of tan(x)?","options":["sec²(x)","-sec²(x)","csc²(x)","-csc²(x)"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for cesium?","options":["C","Ce","Cs","Cm"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Persistence of Memory'?","options":["Salvador Dalí","Pablo Picasso","Joan Miró","René Magritte"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of bat?","options":["Flying Fox","Vampire Bat","Fruit Bat","Horseshoe Bat"],"answer":0,"category":"Nature","difficulty":"hard"},
  {"q":"Who was the first female Prime Minister of Norway?","options":["Gro Harlem Brundtland","Erna Solberg","Kjell Magne Bondevik","Jens Stoltenberg"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"Which country has the most coral reefs?","options":["Australia","Indonesia","Philippines","Mexico"],"answer":1,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's oceans called?","options":["Oceanography","Marine Biology","Hydrology","Limnology"],"answer":0,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most violent storms?","options":["Earth","Jupiter","Saturn","Neptune"],"answer":1,"category":"Space","difficulty":"hard"},
  {"q":"What does HTML stand for?","options":["Hypertext Markup Language","High Tech Markup Language","Hyper Transfer Markup Language","Home Tool Markup Language"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the sum of the first 100 natural numbers?","options":["4950","5050","5150","5250"],"answer":1,"category":"Math","difficulty":"medium"},
  {"q":"What is the chemical symbol for selenium?","options":["S","Se","Sl","Sn"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Starry Night'?","options":["Vincent van Gogh","Pablo Picasso","Claude Monet","Salvador Dalí"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of dolphin?","options":["Bottlenose Dolphin","Killer Whale","Spinner Dolphin","Common Dolphin"],"answer":1,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of Sri Lanka?","options":["Sirimavo Bandaranaike","Chandrika Kumaratunga","Mahinda Rajapaksa","Ranil Wickremesinghe"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the golden ratio conjugate?","options":["0.618","1.618","2.618","3.618"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human body is affected by Parkinson's disease?","options":["Heart","Brain","Lungs","Liver"],"answer":1,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Adventures of Huckleberry Finn'?","options":["Mark Twain","John Steinbeck","Ernest Hemingway","F. Scott Fitzgerald"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for krypton?","options":["K","Ky","Kr","Kp"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most islands in the Caribbean?","options":["Cuba","Jamaica","Bahamas","Grenada"],"answer":2,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's climate called?","options":["Meteorology","Climatology","Atmospheric Science","Geology"],"answer":1,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most tilted magnetic field?","options":["Earth","Jupiter","Saturn","Uranus"],"answer":3,"category":"Space","difficulty":"hard"},
  {"q":"What does CSS stand for?","options":["Cascading Style Sheets","Computer Style Sheets","Creative Style System","Content Styling System"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of arcsin(x)?","options":["1/√(1-x²)","-1/√(1-x²)","1/(1+x²)","-1/(1+x²)"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for xenon?","options":["X","Xe","Xn","Xo"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Birth of Venus'?","options":["Sandro Botticelli","Leonardo da Vinci","Michelangelo","Raphael"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of penguin?","options":["Emperor Penguin","King Penguin","Adélie Penguin","Chinstrap Penguin"],"answer":0,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of the United Kingdom?","options":["Margaret Thatcher","Theresa May","Angela Merkel","Indira Gandhi"],"answer":0,"category":"History","difficulty":"medium"},
  {"q":"What is the value of the sum of the cubes of the first n natural numbers?","options":["[n(n+1)/2]²","n(n+1)(2n+1)/6","n(n+1)/2","n²(n+1)²/4"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human body is affected by diabetes?","options":["Pancreas","Liver","Kidneys","Heart"],"answer":0,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Grapes of Wrath'?","options":["John Steinbeck","Ernest Hemingway","F. Scott Fitzgerald","William Faulkner"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for radon?","options":["R","Ra","Rn","Rd"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most volcanoes in the world?","options":["Indonesia","Japan","United States","Chile"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's magnetic field called?","options":["Geomagnetism","Electromagnetism","Magnetohydrodynamics","Paleomagnetism"],"answer":0,"category":"Science","difficulty":"hard"},
  {"q":"Which planet has the most complex ring system?","options":["Jupiter","Saturn","Uranus","Neptune"],"answer":1,"category":"Space","difficulty":"medium"},
  {"q":"What does SQL stand for?","options":["Structured Query Language","Simple Query Language","Standard Query Language","System Query Language"],"answer":0,"category":"Technology","difficulty":"medium"},
  {"q":"What is the value of the derivative of ln|x|?","options":["1/x","-1/x","1/|x|","-1/|x|"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for boron?","options":["B","Bo","Bn","Br"],"answer":0,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Last Supper'?","options":["Leonardo da Vinci","Michelangelo","Raphael","Donatello"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of turtle?","options":["Leatherback Turtle","Green Sea Turtle","Loggerhead Turtle","Galápagos Tortoise"],"answer":0,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of India?","options":["Indira Gandhi","Sonia Gandhi","Pratibha Patil","Mother Teresa"],"answer":0,"category":"History","difficulty":"medium"},
  {"q":"What is the value of the sum of the first n even numbers?","options":["n(n+1)","n²","2n","n(n+1)/2"],"answer":0,"category":"Math","difficulty":"medium"},
  {"q":"Which part of the human body is affected by asthma?","options":["Heart","Lungs","Brain","Liver"],"answer":1,"category":"Biology","difficulty":"easy"},
  {"q":"Who wrote 'The Sun Also Rises'?","options":["Ernest Hemingway","F. Scott Fitzgerald","John Steinbeck","William Faulkner"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for fluorine?","options":["F","Fl","Fo","Fr"],"answer":0,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most borders with other countries?","options":["Russia","China","Brazil","Germany"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's atmosphere called?","options":["Meteorology","Climatology","Atmospheric Science","Aerology"],"answer":2,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most volcanic activity in the solar system?","options":["Earth","Mars","Venus","Io (moon of Jupiter)"],"answer":3,"category":"Space","difficulty":"hard"},
  {"q":"What does HTTP stand for?","options":["Hypertext Transfer Protocol","High Tech Transfer Protocol","Hyper Transfer Text Protocol","Home Tool Transfer Protocol"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of a constant?","options":["0","1","The constant itself","Undefined"],"answer":0,"category":"Math","difficulty":"medium"},
  {"q":"What is the chemical symbol for manganese?","options":["M","Ma","Mn","Mg"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Luncheon on the Grass'?","options":["Édouard Manet","Claude Monet","Pierre-Auguste Renoir","Paul Cézanne"],"answer":0,"category":"Art","difficulty":"hard"},
  {"q":"What is the largest species of bird of prey?","options":["Bald Eagle","Golden Eagle","Philippine Eagle","Andean Condor"],"answer":3,"category":"Nature","difficulty":"hard"},
  {"q":"Who was the first female Prime Minister of New Zealand?","options":["Jacinda Ardern","Helen Clark","Jenny Shipley","Julia Gillard"],"answer":2,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the sum of the interior angles of a pentagon?","options":["360°","540°","720°","900°"],"answer":1,"category":"Math","difficulty":"medium"},
  {"q":"Which part of the cell is responsible for protein synthesis?","options":["Mitochondria","Nucleus","Ribosomes","Golgi Apparatus"],"answer":2,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Picture of Dorian Gray'?","options":["Oscar Wilde","Bram Stoker","H.G. Wells","Arthur Conan Doyle"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for cobalt?","options":["C","Co","Ct","Cb"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most official languages?","options":["India","South Africa","Bolivia","Zimbabwe"],"answer":3,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the origin and development of the universe called?","options":["Astronomy","Cosmology","Astrophysics","Quantum Mechanics"],"answer":1,"category":"Science","difficulty":"hard"},
  {"q":"Which planet has the most moons in the solar system?","options":["Jupiter","Saturn","Uranus","Neptune"],"answer":1,"category":"Space","difficulty":"medium"},
  {"q":"What does URL stand for?","options":["Uniform Resource Locator","Universal Reference Locator","Uniform Reference Link","Universal Resource Link"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of cos(x)?","options":["sin(x)","-sin(x)","-cos(x)","tan(x)"],"answer":1,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for barium?","options":["B","Ba","Br","Bi"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Sleeping Gypsy'?","options":["Henri Rousseau","Paul Gauguin","Vincent van Gogh","Henri Matisse"],"answer":0,"category":"Art","difficulty":"hard"},
  {"q":"What is the largest species of lizard?","options":["Komodo Dragon","Monitor Lizard","Gila Monster","Iguana"],"answer":0,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of the United Kingdom?","options":["Margaret Thatcher","Theresa May","Angela Merkel","Indira Gandhi"],"answer":0,"category":"History","difficulty":"medium"},
  {"q":"What is the value of the integral of x² dx?","options":["x³/3","x²/2","x³","2x"],"answer":0,"category":"Math","difficulty":"medium"},
  {"q":"Which part of the human eye is responsible for color vision?","options":["Rods","Cones","Iris","Pupil"],"answer":1,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'Wuthering Heights'?","options":["Charlotte Brontë","Emily Brontë","Anne Brontë","Jane Austen"],"answer":1,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for chromium?","options":["C","Ch","Cr","Cm"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most active volcanoes?","options":["Indonesia","Japan","United States","Chile"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's physical structure and substance called?","options":["Geography","Geology","Meteorology","Oceanography"],"answer":1,"category":"Science","difficulty":"easy"},
  {"q":"Which planet has the most elliptical orbit?","options":["Mercury","Venus","Earth","Mars"],"answer":0,"category":"Space","difficulty":"hard"},
  {"q":"What does PHP stand for?","options":["PHP: Hypertext Preprocessor","Personal Home Page","Preprocessed Hypertext Protocol","Public Home Protocol"],"answer":0,"category":"Technology","difficulty":"medium"},
  {"q":"What is the value of the limit of (1 + 1/n)^n as n approaches infinity?","options":["0","1","e","Infinity"],"answer":2,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for lithium?","options":["L","Li","Lt","La"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Son of Man'?","options":["René Magritte","Salvador Dalí","Pablo Picasso","Joan Miró"],"answer":0,"category":"Art","difficulty":"hard"},
  {"q":"What is the largest species of antelope?","options":["Eland","Wildebeest","Impala","Springbok"],"answer":0,"category":"Nature","difficulty":"hard"},
  {"q":"Who was the first female Prime Minister of Canada?","options":["Kim Campbell","Jean Chrétien","Paul Martin","Stephen Harper"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the square root of -1?","options":["-1","0","1","i"],"answer":3,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human brain is responsible for reasoning and planning?","options":["Cerebellum","Brainstem","Frontal Lobe","Occipital Lobe"],"answer":2,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Handmaid's Tale'?","options":["Margaret Atwood","Alice Munro","Donna Tartt","Joyce Carol Oates"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for beryllium?","options":["B","Be","By","Br"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most natural resources?","options":["Russia","United States","China","Saudi Arabia"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the behavior of matter at the atomic and subatomic level called?","options":["Quantum Mechanics","Relativity","Thermodynamics","Electromagnetism"],"answer":0,"category":"Science","difficulty":"hard"},
  {"q":"Which planet has the most intense radiation belts?","options":["Earth","Jupiter","Saturn","Neptune"],"answer":1,"category":"Space","difficulty":"hard"},
  {"q":"What does GUI stand for?","options":["Graphical User Interface","General User Interface","Graphical Utility Interface","General Utility Interface"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of sec(x)?","options":["sec(x)tan(x)","-sec(x)tan(x)","csc(x)cot(x)","-csc(x)cot(x)"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for strontium?","options":["S","Sr","St","Sm"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Kiss'?","options":["Gustav Klimt","Edvard Munch","Egon Schiele","Oskar Kokoschka"],"answer":0,"category":"Art","difficulty":"hard"},
  {"q":"What is the largest species of frog?","options":["Goliath Frog","Bullfrog","Poison Dart Frog","Tree Frog"],"answer":0,"category":"Nature","difficulty":"hard"},
  {"q":"Who was the first female Prime Minister of Australia?","options":["Julia Gillard","Pauline Hanson","Tony Abbott","John Howard"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the sum of the exterior angles of any polygon?","options":["180°","270°","360°","540°"],"answer":2,"category":"Math","difficulty":"medium"},
  {"q":"Which part of the human body produces red blood cells?","options":["Liver","Spleen","Bone Marrow","Kidneys"],"answer":2,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Lord of the Rings'?","options":["C.S. Lewis","J.R.R. Tolkien","George R.R. Martin","J.K. Rowling"],"answer":1,"category":"Literature","difficulty":"easy"},
  {"q":"What is the chemical symbol for radium?","options":["R","Ra","Rd","Rm"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most diverse ecosystem?","options":["Brazil","Australia","Indonesia","Madagascar"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the properties and behavior of light called?","options":["Optics","Acoustics","Thermodynamics","Electromagnetism"],"answer":0,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most intense auroras?","options":["Earth","Jupiter","Saturn","Neptune"],"answer":1,"category":"Space","difficulty":"hard"},
  {"q":"What does FTP stand for?","options":["File Transfer Protocol","File Transmission Protocol","File Transport Protocol","File Translation Protocol"],"answer":0,"category":"Technology","difficulty":"medium"},
  {"q":"What is the value of the derivative of tan(x)?","options":["sec²(x)","-sec²(x)","csc²(x)","-csc²(x)"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for cesium?","options":["C","Ce","Cs","Cm"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Persistence of Memory'?","options":["Salvador Dalí","Pablo Picasso","Joan Miró","René Magritte"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of bat?","options":["Flying Fox","Vampire Bat","Fruit Bat","Horseshoe Bat"],"answer":0,"category":"Nature","difficulty":"hard"},
  {"q":"Who was the first female Prime Minister of Norway?","options":["Gro Harlem Brundtland","Erna Solberg","Kjell Magne Bondevik","Jens Stoltenberg"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the product of the first 10 prime numbers?","options":["210","2310","30030","510510"],"answer":2,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human body is affected by glaucoma?","options":["Ears","Eyes","Heart","Lungs"],"answer":1,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Catcher in the Rye'?","options":["J.D. Salinger","F. Scott Fitzgerald","Ernest Hemingway","John Steinbeck"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for arsenic?","options":["A","Ar","As","An"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most coral reefs?","options":["Australia","Indonesia","Philippines","Mexico"],"answer":1,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's oceans called?","options":["Oceanography","Marine Biology","Hydrology","Limnology"],"answer":0,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most violent storms?","options":["Earth","Jupiter","Saturn","Neptune"],"answer":1,"category":"Space","difficulty":"hard"},
  {"q":"What does HTML stand for?","options":["Hypertext Markup Language","High Tech Markup Language","Hyper Transfer Markup Language","Home Tool Markup Language"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the sum of the first 100 natural numbers?","options":["4950","5050","5150","5250"],"answer":1,"category":"Math","difficulty":"medium"},
  {"q":"What is the chemical symbol for selenium?","options":["S","Se","Sl","Sn"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Starry Night'?","options":["Vincent van Gogh","Pablo Picasso","Claude Monet","Salvador Dalí"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of dolphin?","options":["Bottlenose Dolphin","Killer Whale","Spinner Dolphin","Common Dolphin"],"answer":1,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of Sri Lanka?","options":["Sirimavo Bandaranaike","Chandrika Kumaratunga","Mahinda Rajapaksa","Ranil Wickremesinghe"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the golden ratio conjugate?","options":["0.618","1.618","2.618","3.618"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human body is affected by Parkinson's disease?","options":["Heart","Brain","Lungs","Liver"],"answer":1,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Adventures of Huckleberry Finn'?","options":["Mark Twain","John Steinbeck","Ernest Hemingway","F. Scott Fitzgerald"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for krypton?","options":["K","Ky","Kr","Kp"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most islands in the Caribbean?","options":["Cuba","Jamaica","Bahamas","Grenada"],"answer":2,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's climate called?","options":["Meteorology","Climatology","Atmospheric Science","Geology"],"answer":1,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most tilted magnetic field?","options":["Earth","Jupiter","Saturn","Uranus"],"answer":3,"category":"Space","difficulty":"hard"},
  {"q":"What does CSS stand for?","options":["Cascading Style Sheets","Computer Style Sheets","Creative Style System","Content Styling System"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of arcsin(x)?","options":["1/√(1-x²)","-1/√(1-x²)","1/(1+x²)","-1/(1+x²)"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for xenon?","options":["X","Xe","Xn","Xo"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Birth of Venus'?","options":["Sandro Botticelli","Leonardo da Vinci","Michelangelo","Raphael"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of penguin?","options":["Emperor Penguin","King Penguin","Adélie Penguin","Chinstrap Penguin"],"answer":0,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of the United Kingdom?","options":["Margaret Thatcher","Theresa May","Angela Merkel","Indira Gandhi"],"answer":0,"category":"History","difficulty":"medium"},
  {"q":"What is the value of the sum of the cubes of the first n natural numbers?","options":["[n(n+1)/2]²","n(n+1)(2n+1)/6","n(n+1)/2","n²(n+1)²/4"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human body is affected by diabetes?","options":["Pancreas","Liver","Kidneys","Heart"],"answer":0,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Grapes of Wrath'?","options":["John Steinbeck","Ernest Hemingway","F. Scott Fitzgerald","William Faulkner"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for radon?","options":["R","Ra","Rn","Rd"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most volcanoes in the world?","options":["Indonesia","Japan","United States","Chile"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's magnetic field called?","options":["Geomagnetism","Electromagnetism","Magnetohydrodynamics","Paleomagnetism"],"answer":0,"category":"Science","difficulty":"hard"},
  {"q":"Which planet has the most complex ring system?","options":["Jupiter","Saturn","Uranus","Neptune"],"answer":1,"category":"Space","difficulty":"medium"},
  {"q":"What does SQL stand for?","options":["Structured Query Language","Simple Query Language","Standard Query Language","System Query Language"],"answer":0,"category":"Technology","difficulty":"medium"},
  {"q":"What is the value of the derivative of ln|x|?","options":["1/x","-1/x","1/|x|","-1/|x|"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for boron?","options":["B","Bo","Bn","Br"],"answer":0,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Last Supper'?","options":["Leonardo da Vinci","Michelangelo","Raphael","Donatello"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of turtle?","options":["Leatherback Turtle","Green Sea Turtle","Loggerhead Turtle","Galápagos Tortoise"],"answer":0,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of India?","options":["Indira Gandhi","Sonia Gandhi","Pratibha Patil","Mother Teresa"],"answer":0,"category":"History","difficulty":"medium"},
  {"q":"What is the value of the sum of the first n even numbers?","options":["n(n+1)","n²","2n","n(n+1)/2"],"answer":0,"category":"Math","difficulty":"medium"},
  {"q":"Which part of the human body is affected by asthma?","options":["Heart","Lungs","Brain","Liver"],"answer":1,"category":"Biology","difficulty":"easy"},
  {"q":"Who wrote 'The Sun Also Rises'?","options":["Ernest Hemingway","F. Scott Fitzgerald","John Steinbeck","William Faulkner"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for fluorine?","options":["F","Fl","Fo","Fr"],"answer":0,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most borders with other countries?","options":["Russia","China","Brazil","Germany"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's atmosphere called?","options":["Meteorology","Climatology","Atmospheric Science","Aerology"],"answer":2,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most volcanic activity in the solar system?","options":["Earth","Mars","Venus","Io (moon of Jupiter)"],"answer":3,"category":"Space","difficulty":"hard"},
  {"q":"What does HTTP stand for?","options":["Hypertext Transfer Protocol","High Tech Transfer Protocol","Hyper Transfer Text Protocol","Home Tool Transfer Protocol"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of a constant?","options":["0","1","The constant itself","Undefined"],"answer":0,"category":"Math","difficulty":"medium"},
  {"q":"What is the chemical symbol for manganese?","options":["M","Ma","Mn","Mg"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Luncheon on the Grass'?","options":["Édouard Manet","Claude Monet","Pierre-Auguste Renoir","Paul Cézanne"],"answer":0,"category":"Art","difficulty":"hard"},
  {"q":"What is the largest species of bird of prey?","options":["Bald Eagle","Golden Eagle","Philippine Eagle","Andean Condor"],"answer":3,"category":"Nature","difficulty":"hard"},
  {"q":"Who was the first female Prime Minister of New Zealand?","options":["Jacinda Ardern","Helen Clark","Jenny Shipley","Julia Gillard"],"answer":2,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the sum of the interior angles of a pentagon?","options":["360°","540°","720°","900°"],"answer":1,"category":"Math","difficulty":"medium"},
  {"q":"Which part of the cell is responsible for protein synthesis?","options":["Mitochondria","Nucleus","Ribosomes","Golgi Apparatus"],"answer":2,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Picture of Dorian Gray'?","options":["Oscar Wilde","Bram Stoker","H.G. Wells","Arthur Conan Doyle"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for cobalt?","options":["C","Co","Ct","Cb"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most official languages?","options":["India","South Africa","Bolivia","Zimbabwe"],"answer":3,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the origin and development of the universe called?","options":["Astronomy","Cosmology","Astrophysics","Quantum Mechanics"],"answer":1,"category":"Science","difficulty":"hard"},
  {"q":"Which planet has the most moons in the solar system?","options":["Jupiter","Saturn","Uranus","Neptune"],"answer":1,"category":"Space","difficulty":"medium"},
  {"q":"What does URL stand for?","options":["Uniform Resource Locator","Universal Reference Locator","Uniform Reference Link","Universal Resource Link"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of cos(x)?","options":["sin(x)","-sin(x)","-cos(x)","tan(x)"],"answer":1,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for barium?","options":["B","Ba","Br","Bi"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Sleeping Gypsy'?","options":["Henri Rousseau","Paul Gauguin","Vincent van Gogh","Henri Matisse"],"answer":0,"category":"Art","difficulty":"hard"},
  {"q":"What is the largest species of lizard?","options":["Komodo Dragon","Monitor Lizard","Gila Monster","Iguana"],"answer":0,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of the United Kingdom?","options":["Margaret Thatcher","Theresa May","Angela Merkel","Indira Gandhi"],"answer":0,"category":"History","difficulty":"medium"},
  {"q":"What is the value of the integral of x² dx?","options":["x³/3","x²/2","x³","2x"],"answer":0,"category":"Math","difficulty":"medium"},
  {"q":"Which part of the human eye is responsible for color vision?","options":["Rods","Cones","Iris","Pupil"],"answer":1,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'Wuthering Heights'?","options":["Charlotte Brontë","Emily Brontë","Anne Brontë","Jane Austen"],"answer":1,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for chromium?","options":["C","Ch","Cr","Cm"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most active volcanoes?","options":["Indonesia","Japan","United States","Chile"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's physical structure and substance called?","options":["Geography","Geology","Meteorology","Oceanography"],"answer":1,"category":"Science","difficulty":"easy"},
  {"q":"Which planet has the most elliptical orbit?","options":["Mercury","Venus","Earth","Mars"],"answer":0,"category":"Space","difficulty":"hard"},
  {"q":"What does PHP stand for?","options":["PHP: Hypertext Preprocessor","Personal Home Page","Preprocessed Hypertext Protocol","Public Home Protocol"],"answer":0,"category":"Technology","difficulty":"medium"},
  {"q":"What is the value of the limit of (1 + 1/n)^n as n approaches infinity?","options":["0","1","e","Infinity"],"answer":2,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for lithium?","options":["L","Li","Lt","La"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Son of Man'?","options":["René Magritte","Salvador Dalí","Pablo Picasso","Joan Miró"],"answer":0,"category":"Art","difficulty":"hard"},
  {"q":"What is the largest species of antelope?","options":["Eland","Wildebeest","Impala","Springbok"],"answer":0,"category":"Nature","difficulty":"hard"},
  {"q":"Who was the first female Prime Minister of Canada?","options":["Kim Campbell","Jean Chrétien","Paul Martin","Stephen Harper"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the square root of -1?","options":["-1","0","1","i"],"answer":3,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human brain is responsible for reasoning and planning?","options":["Cerebellum","Brainstem","Frontal Lobe","Occipital Lobe"],"answer":2,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Handmaid's Tale'?","options":["Margaret Atwood","Alice Munro","Donna Tartt","Joyce Carol Oates"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for beryllium?","options":["B","Be","By","Br"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most natural resources?","options":["Russia","United States","China","Saudi Arabia"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the behavior of matter at the atomic and subatomic level called?","options":["Quantum Mechanics","Relativity","Thermodynamics","Electromagnetism"],"answer":0,"category":"Science","difficulty":"hard"},
  {"q":"Which planet has the most intense radiation belts?","options":["Earth","Jupiter","Saturn","Neptune"],"answer":1,"category":"Space","difficulty":"hard"},
  {"q":"What does GUI stand for?","options":["Graphical User Interface","General User Interface","Graphical Utility Interface","General Utility Interface"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of sec(x)?","options":["sec(x)tan(x)","-sec(x)tan(x)","csc(x)cot(x)","-csc(x)cot(x)"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for strontium?","options":["S","Sr","St","Sm"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Kiss'?","options":["Gustav Klimt","Edvard Munch","Egon Schiele","Oskar Kokoschka"],"answer":0,"category":"Art","difficulty":"hard"},
  {"q":"What is the largest species of frog?","options":["Goliath Frog","Bullfrog","Poison Dart Frog","Tree Frog"],"answer":0,"category":"Nature","difficulty":"hard"},
  {"q":"Who was the first female Prime Minister of Australia?","options":["Julia Gillard","Pauline Hanson","Tony Abbott","John Howard"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the sum of the exterior angles of any polygon?","options":["180°","270°","360°","540°"],"answer":2,"category":"Math","difficulty":"medium"},
  {"q":"Which part of the human body produces red blood cells?","options":["Liver","Spleen","Bone Marrow","Kidneys"],"answer":2,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Lord of the Rings'?","options":["C.S. Lewis","J.R.R. Tolkien","George R.R. Martin","J.K. Rowling"],"answer":1,"category":"Literature","difficulty":"easy"},
  {"q":"What is the chemical symbol for radium?","options":["R","Ra","Rd","Rm"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most diverse ecosystem?","options":["Brazil","Australia","Indonesia","Madagascar"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the properties and behavior of light called?","options":["Optics","Acoustics","Thermodynamics","Electromagnetism"],"answer":0,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most intense auroras?","options":["Earth","Jupiter","Saturn","Neptune"],"answer":1,"category":"Space","difficulty":"hard"},
  {"q":"What does FTP stand for?","options":["File Transfer Protocol","File Transmission Protocol","File Transport Protocol","File Translation Protocol"],"answer":0,"category":"Technology","difficulty":"medium"},
  {"q":"What is the value of the derivative of tan(x)?","options":["sec²(x)","-sec²(x)","csc²(x)","-csc²(x)"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for cesium?","options":["C","Ce","Cs","Cm"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Persistence of Memory'?","options":["Salvador Dalí","Pablo Picasso","Joan Miró","René Magritte"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of bat?","options":["Flying Fox","Vampire Bat","Fruit Bat","Horseshoe Bat"],"answer":0,"category":"Nature","difficulty":"hard"},
  {"q":"Who was the first female Prime Minister of Norway?","options":["Gro Harlem Brundtland","Erna Solberg","Kjell Magne Bondevik","Jens Stoltenberg"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the product of the first 10 prime numbers?","options":["210","2310","30030","510510"],"answer":2,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human body is affected by glaucoma?","options":["Ears","Eys","Heart","Lungs"],"answer":1,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Catcher in the Rye'?","options":["J.D. Salinger","F. Scott Fitzgerald","Ernest Hemingway","John Steinbeck"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for arsenic?","options":["A","Ar","As","An"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most coral reefs?","options":["Australia","Indonesia","Philippines","Mexico"],"answer":1,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's oceans called?","options":["Oceanography","Marine Biology","Hydrology","Limnology"],"answer":0,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most violent storms?","options":["Earth","Jupiter","Saturn","Neptune"],"answer":1,"category":"Space","difficulty":"hard"},
  {"q":"What does HTML stand for?","options":["Hypertext Markup Language","High Tech Markup Language","Hyper Transfer Markup Language","Home Tool Markup Language"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the sum of the first 100 natural numbers?","options":["4950","5050","5150","5250"],"answer":1,"category":"Math","difficulty":"medium"},
  {"q":"What is the chemical symbol for selenium?","options":["S","Se","Sl","Sn"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Starry Night'?","options":["Vincent van Gogh","Pablo Picasso","Claude Monet","Salvador Dalí"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of dolphin?","options":["Bottlenose Dolphin","Killer Whale","Spinner Dolphin","Common Dolphin"],"answer":1,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of Sri Lanka?","options":["Sirimavo Bandaranaike","Chandrika Kumaratunga","Mahinda Rajapaksa","Ranil Wickremesinghe"],"answer":0,"category":"History","difficulty":"hard"},
  {"q":"What is the value of the golden ratio conjugate?","options":["0.618","1.618","2.618","3.618"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human body is affected by Parkinson's disease?","options":["Heart","Brain","Lungs","Liver"],"answer":1,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Adventures of Huckleberry Finn'?","options":["Mark Twain","John Steinbeck","Ernest Hemingway","F. Scott Fitzgerald"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for krypton?","options":["K","Ky","Kr","Kp"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most islands in the Caribbean?","options":["Cuba","Jamaica","Bahamas","Grenada"],"answer":2,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's climate called?","options":["Meteorology","Climatology","Atmospheric Science","Geology"],"answer":1,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most tilted magnetic field?","options":["Earth","Jupiter","Saturn","Uranus"],"answer":3,"category":"Space","difficulty":"hard"},
  {"q":"What does CSS stand for?","options":["Cascading Style Sheets","Computer Style Sheets","Creative Style System","Content Styling System"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of arcsin(x)?","options":["1/√(1-x²)","-1/√(1-x²)","1/(1+x²)","-1/(1+x²)"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for xenon?","options":["X","Xe","Xn","Xo"],"answer":1,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Birth of Venus'?","options":["Sandro Botticelli","Leonardo da Vinci","Michelangelo","Raphael"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of penguin?","options":["Emperor Penguin","King Penguin","Adélie Penguin","Chinstrap Penguin"],"answer":0,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of the United Kingdom?","options":["Margaret Thatcher","Theresa May","Angela Merkel","Indira Gandhi"],"answer":0,"category":"History","difficulty":"medium"},
  {"q":"What is the value of the sum of the cubes of the first n natural numbers?","options":["[n(n+1)/2]²","n(n+1)(2n+1)/6","n(n+1)/2","n²(n+1)²/4"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"Which part of the human body is affected by diabetes?","options":["Pancreas","Liver","Kidneys","Heart"],"answer":0,"category":"Biology","difficulty":"medium"},
  {"q":"Who wrote 'The Grapes of Wrath'?","options":["John Steinbeck","Ernest Hemingway","F. Scott Fitzgerald","William Faulkner"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for radon?","options":["R","Ra","Rn","Rd"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most volcanoes in the world?","options":["Indonesia","Japan","United States","Chile"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's magnetic field called?","options":["Geomagnetism","Electromagnetism","Magnetohydrodynamics","Paleomagnetism"],"answer":0,"category":"Science","difficulty":"hard"},
  {"q":"Which planet has the most complex ring system?","options":["Jupiter","Saturn","Uranus","Neptune"],"answer":1,"category":"Space","difficulty":"medium"},
  {"q":"What does SQL stand for?","options":["Structured Query Language","Simple Query Language","Standard Query Language","System Query Language"],"answer":0,"category":"Technology","difficulty":"medium"},
  {"q":"What is the value of the derivative of ln|x|?","options":["1/x","-1/x","1/|x|","-1/|x|"],"answer":0,"category":"Math","difficulty":"hard"},
  {"q":"What is the chemical symbol for boron?","options":["B","Bo","Bn","Br"],"answer":0,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Last Supper'?","options":["Leonardo da Vinci","Michelangelo","Raphael","Donatello"],"answer":0,"category":"Art","difficulty":"medium"},
  {"q":"What is the largest species of turtle?","options":["Leatherback Turtle","Green Sea Turtle","Loggerhead Turtle","Galápagos Tortoise"],"answer":0,"category":"Nature","difficulty":"medium"},
  {"q":"Who was the first female Prime Minister of India?","options":["Indira Gandhi","Sonia Gandhi","Pratibha Patil","Mother Teresa"],"answer":0,"category":"History","difficulty":"medium"},
  {"q":"What is the value of the sum of the first n even numbers?","options":["n(n+1)","n²","2n","n(n+1)/2"],"answer":0,"category":"Math","difficulty":"medium"},
  {"q":"Which part of the human body is affected by asthma?","options":["Heart","Lungs","Brain","Liver"],"answer":1,"category":"Biology","difficulty":"easy"},
  {"q":"Who wrote 'The Sun Also Rises'?","options":["Ernest Hemingway","F. Scott Fitzgerald","John Steinbeck","William Faulkner"],"answer":0,"category":"Literature","difficulty":"medium"},
  {"q":"What is the chemical symbol for fluorine?","options":["F","Fl","Fo","Fr"],"answer":0,"category":"Chemistry","difficulty":"easy"},
  {"q":"Which country has the most borders with other countries?","options":["Russia","China","Brazil","Germany"],"answer":0,"category":"Geography","difficulty":"hard"},
  {"q":"What is the study of the Earth's atmosphere called?","options":["Meteorology","Climatology","Atmospheric Science","Aerology"],"answer":2,"category":"Science","difficulty":"medium"},
  {"q":"Which planet has the most volcanic activity in the solar system?","options":["Earth","Mars","Venus","Io (moon of Jupiter)"],"answer":3,"category":"Space","difficulty":"hard"},
  {"q":"What does HTTP stand for?","options":["Hypertext Transfer Protocol","High Tech Transfer Protocol","Hyper Transfer Text Protocol","Home Tool Transfer Protocol"],"answer":0,"category":"Technology","difficulty":"easy"},
  {"q":"What is the value of the derivative of a constant?","options":["0","1","The constant itself","Undefined"],"answer":0,"category":"Math","difficulty":"medium"},
  {"q":"What is the chemical symbol for manganese?","options":["M","Ma","Mn","Mg"],"answer":2,"category":"Chemistry","difficulty":"easy"},
  {"q":"Who painted 'The Luncheon on the Grass'?","options":["Édouard Manet","Claude Monet","Pierre-Auguste Renoir","Paul Cézanne"],"answer":0,"category":"Art","difficulty":"hard"},
  {"q":"What is the largest species of bird of prey?","options":["Bald Eagle","Golden Eagle","Philippine Eagle","Andean Condor"],"answer":3,"category":"Nature","difficulty":"hard"},
]
