QUESTIONS = [
    {"q":"How many players are on a standard soccer team on the field at one time?","options":["9","10","11","12"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"In which sport would you perform a slam dunk?","options":["Tennis","Basketball","Golf","Cricket"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"What color card signifies a sending-off in soccer?","options":["Blue","Yellow","Green","Red"],"answer":3,"category":"Sports","difficulty":"easy"},
    {"q":"In tennis, what is the score called when both players have 40?","options":["Deuce","Advantage","Love","Tie"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"Which of these is a type of wrestling hold?","options":["Birdie","Eagle","Albatross","Half Nelson"],"answer":3,"category":"Sports","difficulty":"easy"},
    {"q":"Which sport uses a shuttlecock?","options":["Badminton","Tennis","Squash","Pickleball"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"In American football, how many points is a touchdown worth?","options":["3","6","7","8"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"Which country won the 2018 FIFA World Cup?","options":["Germany","Brazil","France","Croatia"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"In bowling, what is it called when you knock down all pins with two balls?","options":["Strike","Spare","Gutter","Split"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"What is the name of the trophy awarded to the winner of the NHL playoffs?","options":["Vince Lombardi Trophy","Larry O'Brien Trophy","Stanley Cup","Commissioner's Trophy"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"In golf, what is the term for a score of one under par on a hole?","options":["Eagle","Birdie","Bogey","Par"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"Which sport is associated with Wimbledon?","options":["Golf","Tennis","Cricket","Rugby"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"Which of these is NOT a track and field event?","options":["Shot Put","Javelin","Triple Jump","Slalom"],"answer":3,"category":"Sports","difficulty":"easy"},
    {"q":"How many rings are on the Olympic flag?","options":["4","5","6","7"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"Which baseball term means a batter has been struck out three times in one game?","options":["Golden Sombrero","Hat Trick","Turkey","Strikeout Triplet"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"In basketball, how many points is a free throw worth?","options":["1","2","3","4"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"What is the maximum break possible in a game of snooker?","options":["147","155","100","127"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"Which boxer was known as 'The Greatest' and 'The People's Champion'?","options":["Mike Tyson","Sugar Ray Leonard","Muhammad Ali","George Foreman"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"Which of these is a position in baseball?","options":["Goalkeeper","Shortstop","Flanker","Point Guard"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"What is the name of the major tennis tournament held in Paris?","options":["Wimbledon","US Open","Australian Open","French Open"],"answer":3,"category":"Sports","difficulty":"easy"},
    {"q":"Which NBA player holds the record for the most career points?","options":["Kareem Abdul-Jabbar","LeBron James","Kobe Bryant","Michael Jordan"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"In cricket, how many balls are typically bowled in an over?","options":["4","5","6","7"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"Which nation won the first-ever FIFA World Cup in 1930?","options":["Brazil","Italy","Uruguay","Argentina"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"What is the distance, in meters, of a marathon?","options":["26.2 km","42.195 km","50 km","21.1 km"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"In American football, which position is responsible for snapping the ball to the quarterback?","options":["Guard","Tackle","Tight End","Center"],"answer":3,"category":"Sports","difficulty":"medium"},
    {"q":"Which golfer was the first to achieve the career Grand Slam?","options":["Tiger Woods","Jack Nicklaus","Gene Sarazen","Ben Hogan"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"Which country has won the most Rugby World Cups?","options":["New Zealand","Australia","South Africa","England"],"answer":0,"category":"Sports","difficulty":"medium"},
    {"q":"What does NASCAR stand for?","options":["National Association of Stock Car Auto Racing","National Auto Sport Competition and Racing","North American Speed Circuit Auto Racing","National Association for Speed Competition and Racing"],"answer":0,"category":"Sports","difficulty":"medium"},
    {"q":"Which tennis player holds the record for the most Grand Slam singles titles (men's)?","options":["Roger Federer","Rafael Nadal","Novak Djokovic","Pete Sampras"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"In fencing, what is the name of the sword with a flexible blade and a small guard?","options":["Épée","Sabre","Foil","Rapier"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"Which NFL team calls Lambeau Field home?","options":["Chicago Bears","Dallas Cowboys","Pittsburgh Steelers","Green Bay Packers"],"answer":3,"category":"Sports","difficulty":"medium"},
    {"q":"What is the term for a score of 100 points or more in a single innings by a batsman in cricket?","options":["Ton","Double Ton","Century","Hundred"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"Which boxer remained undefeated throughout his professional career?","options":["Mike Tyson","Rocky Marciano","Floyd Mayweather Jr.","Muhammad Ali"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"In the Olympics, what color are the rings on a black background?","options":["All White","Blue, Black, Red, Yellow, Green","Blue, Yellow, Black, Green, Red","Red, White, and Blue"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"Which sport uses terms like 'scrum', 'ruck', and 'maul'?","options":["Soccer","Rugby Union","Australian Rules Football","Gaelic Football"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Who was the first gymnast to score a perfect 10 in the Olympics?","options":["Simone Biles","Nadia Comăneci","Mary Lou Retton","Olga Korbut"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Which baseball team did Babe Ruth famously play for?","options":["Boston Red Sox","Chicago Cubs","New York Yankees","St. Louis Cardinals"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"What is the name of the horse that won the Triple Crown in 1973?","options":["American Pharoah","War Admiral","Secretariat","Seattle Slew"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"In curling, what is the name of the person who pushes the stone?","options":["Sweeper","Skip","Lead","Thrower"],"answer":3,"category":"Sports","difficulty":"medium"},
    {"q":"Which country has won the most medals in the Summer Olympics?","options":["China","Soviet Union","Great Britain","United States"],"answer":3,"category":"Sports","difficulty":"medium"},
    {"q":"Who is the only boxer to have won the world heavyweight championship three times?","options":["Muhammad Ali","Evander Holyfield","Lennox Lewis","George Foreman"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"Which driver has the most Formula One World Championship titles?","options":["Michael Schumacher","Lewis Hamilton","Juan Manuel Fangio","Ayrton Senna"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which NFL team was known as the 'Washington Football Team' from 2020 to 2022?","options":["Washington Redskins","Washington Commanders","Washington Warriors","Washington Senators"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Who was the first African American to play in Major League Baseball in the modern era?","options":["Satchel Paige","Hank Aaron","Jackie Robinson","Willie Mays"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"In what year were the first modern Olympic Games held?","options":["1886","1896","1900","1912"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which country won the 1995 Rugby World Cup, hosted in South Africa?","options":["New Zealand","England","Australia","South Africa"],"answer":3,"category":"Sports","difficulty":"hard"},
    {"q":"What is the name of the stadium that hosts the annual Masters golf tournament?","options":["Pebble Beach","Augusta National","St. Andrews","Pinehurst"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which NBA team drafted Kobe Bryant, before trading him to the Los Angeles Lakers?","options":["Charlotte Hornets","Vancouver Grizzlies","New Jersey Nets","Philadelphia 76ers"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"Who is the all-time leading goal scorer in FIFA World Cup history?","options":["Pele","Miroslav Klose","Ronaldo","Gerd Müller"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"In Australian Rules Football (AFL), how many points is a goal worth?","options":["1","3","6","9"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"Which pitcher threw a perfect game in the 1956 World Series?","options":["Sandy Koufax","Whitey Ford","Don Larsen","Warren Spahn"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"Which nation won the first-ever Cricket World Cup in 1975?","options":["Australia","England","West Indies","India"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"What is the maximum weight, in pounds, for a flyweight boxer?","options":["105 lbs","108 lbs","112 lbs","115 lbs"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"Which city has hosted the Summer Olympics three times?","options":["Athens","Paris","Los Angeles","London"],"answer":3,"category":"Sports","difficulty":"hard"},
    {"q":"Who was the first woman to run a marathon in under 2 hours and 20 minutes?","options":["Paula Radcliffe","Grete Waitz","Joan Benoit","Tegla Loroupe"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"In what year was the first Monday Night Football game broadcast?","options":["1965","1970","1975","1980"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which tennis player won the 'Calendar Year Golden Slam' (all four Grand Slams and Olympic Gold in one year)?","options":["Steffi Graf","Serena Williams","Andre Agassi","Rafael Nadal"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"Which cyclist has won the most Tour de France titles?","options":["Lance Armstrong","Miguel Indurain","Bernard Hinault","Eddy Merckx"],"answer":3,"category":"Sports","difficulty":"hard"},
    {"q":"What was the original name of the New York Knicks?","options":["New York Americans","New York Gothams","New York Knickerbockers","New York Emperors"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"Which country won the most gold medals at the 2008 Beijing Olympics?","options":["United States","Russia","China","Great Britain"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"In basketball, how many players from each team are on the court at one time?","options":["4","5","6","7"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"Which sport is played at Wimbledon?","options":["Golf","Tennis","Cricket","Rugby"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"What is the name of the trophy awarded to the winner of the Super Bowl?","options":["The Lombardi Trophy","The Stanley Cup","The Vince McMahon Trophy","The Commissioner's Trophy"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"In which sport might you perform a 'butterfly' stroke?","options":["Running","Swimming","Gymnastics","Boxing"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"What is the name of the area where you play ice hockey?","options":["Pitch","Court","Diamond","Rink"],"answer":3,"category":"Sports","difficulty":"easy"},
    {"q":"Which of these is a score in tennis?","options":["Birdie","Eagle","Love","Bogey"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"Which country is famous for originating the sport of sumo wrestling?","options":["China","Mongolia","South Korea","Japan"],"answer":3,"category":"Sports","difficulty":"easy"},
    {"q":"In baseball, how many strikes result in a batter being out?","options":["1","2","3","4"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"Which of these is NOT a piece of equipment in cricket?","options":["Bat","Wicket","Puck","Ball"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"What color is the center of an Olympic archery target?","options":["Red","Blue","Yellow","Gold"],"answer":3,"category":"Sports","difficulty":"easy"},
    {"q":"Which NBA team has won the most championships?","options":["Boston Celtics","Los Angeles Lakers","Chicago Bulls","Golden State Warriors"],"answer":0,"category":"Sports","difficulty":"medium"},
    {"q":"In golf, what is the term for a score of two under par on a single hole?","options":["Birdie","Eagle","Albatross","Condor"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Which nation won the 2010 FIFA World Cup?","options":["Germany","Spain","Netherlands","Brazil"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"In American football, what is it called when the defense catches a forward pass?","options":["Fumble","Sack","Interception","Turnover"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"Which tennis player has won the most Grand Slam singles titles in the Open Era?","options":["Serena Williams","Steffi Graf","Margaret Court","Martina Navratilova"],"answer":0,"category":"Sports","difficulty":"medium"},
    {"q":"What is the distance, in miles, of the Kentucky Derby horse race?","options":["1 mile","1.25 miles","1.5 miles","2 miles"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Which of these is an Olympic swimming event?","options":["100m Backstroke","200m Hurdles","4x100m Relay","Javelin Throw"],"answer":0,"category":"Sports","difficulty":"medium"},
    {"q":"Who is often referred to as 'The Great One' in ice hockey?","options":["Wayne Gretzky","Mario Lemieux","Bobby Orr","Gordie Howe"],"answer":0,"category":"Sports","difficulty":"medium"},
    {"q":"In volleyball, how many touches is a team allowed before they must send the ball over the net?","options":["2","3","4","5"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Which boxer infamously bit off a piece of Evander Holyfield's ear?","options":["Lennox Lewis","Mike Tyson","George Foreman","Riddick Bowe"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Who was the first golfer to win all four major championships (Masters, U.S. Open, Open Championship, PGA) in a single calendar year?","options":["Tiger Woods","Jack Nicklaus","Bobby Jones","Gene Sarazen"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"Which NFL quarterback holds the record for most career passing yards?","options":["Tom Brady","Peyton Manning","Drew Brees","Brett Favre"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"Which country won the inaugural ICC ricket World Cup in 1975?","options":["Australia","India","West Indies","England"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"In what year did the New York Yankees trade Babe Ruth to the Boston Red Sox?","options":["1918","1919","1920","1921"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"Which driver won the Formula One World Championship in 1994, shortly before his fatal crash at Imola?","options":["Ayrton Senna","Alain Prost","Michael Schumacher","Damon Hill"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"What is the maximum break (perfect score) in a frame of snooker?","options":["127","137","147","157"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"Which city hosted the Summer Olympic Games in 2000?","options":["Athens","Beijing","Sydney","Atlanta"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"Who is the only player to have won the FIFA World Cup, the UEFA Champions League, the Ballon d'Or, and the Copa América?","options":["Lionel Messi","Zinedine Zidane","Ronaldo","Pelé"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"In the sport of curling, what is the name of the 'house' that teams aim for?","options":["The Target","The Button","The Bullseye","The Rings"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which NBA player scored 100 points in a single game in 1962?","options":["Wilt Chamberlain","Kobe Bryant","Elgin Baylor","Michael Jordan"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"In which sport would you use the terms 'gutter' and 'split'?","options":["Darts","Bowling","Pool","Shooting"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"What is the name of the major golf tournament held annually in Augusta, Georgia?","options":["The U.S. Open","The Open Championship","The PGA Championship","The Masters"],"answer":3,"category":"Sports","difficulty":"easy"},
    {"q":"Which of these is a position in soccer?","options":["Point Guard","Striker","Catcher","Blocker"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"What piece is moved in a 'checkmate' to end a game of chess?","options":["Pawn","Rook","Bishop","King"],"answer":3,"category":"Sports","difficulty":"easy"},
    {"q":"In the Olympics, what color are the goal posts in field hockey?","options":["White","Yellow","Orange","Blue"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"Which MLB team broke an 86-year championship drought by winning the World Series in 2004?","options":["Chicago Cubs","Boston Red Sox","Chicago White Sox","Los Angeles Dodgers"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"What is the nickname of the University of Alabama's athletic teams?","options":["Tigers","Bulldogs","Crimson Tide","Volunteers"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"In surfing, what does it mean to 'shoot the tube'?","options":["Wipe out","Catch a big wave","Ride inside the breaking part of the wave","Perform a trick"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"Which nation is the all-time leader in Olympic gold medals for the sport of alpine skiing?","options":["Switzerland","United States","Austria","France"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"In rugby union, how many points is a try worth?","options":["3","5","7","10"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Who was the first woman to run a sub-2:20:00 marathon?","options":["Grete Waitz","Paula Radcliffe","Joan Benoit Samuelson","Tegla Loroupe"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which two countries contested the first-ever international soccer match in 1872?","options":["England vs. Scotland","England vs. Wales","Argentina vs. Uruguay","France vs. Belgium"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"Which pitcher holds the MLB record for the most career strikeouts?","options":["Nolan Ryan","Randy Johnson","Roger Clemens","Steve Carlton"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"In which year did Michael Jordan win his first NBA championship?","options":["1988","1991","1993","1996"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which country won the first-ever Rugby World Cup in 1987?","options":["South Africa","Australia","New Zealand","England"],"answer":2,"category":"Sports","difficulty":"hard"},
    {"q":"In which sport would you use a 'puck'?","options":["Hockey","Basketball","Tennis","Soccer"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"How many rounds are in a professional boxing match?","options":["8","10","12","15"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"Which country won the 2014 FIFA World Cup?","options":["Germany","Argentina","Brazil","Spain"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"In basketball, what is it called when a player scores by jumping and putting the ball through the hoop?","options":["Slam Dunk","Layup","Jump Shot","Hook Shot"],"answer":0,"category":"Sports","difficulty":"easy"},
    {"q":"Which sport uses terms like 'strike', 'spare', and 'gutter ball'?","options":["Baseball","Bowling","Golf","Cricket"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"Which NBA player is known as 'The Greek Freak'?","options":["Giannis Antetokounmpo","Luka Dončić","Nikola Jokić","Joel Embiid"],"answer":0,"category":"Sports","difficulty":"medium"},
    {"q":"In golf, what is the term for a score of three under par on a single hole?","options":["Eagle","Albatross","Condor","Birdie"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Which nation has won the most Rugby World Cups?","options":["New Zealand","South Africa","Australia","England"],"answer":0,"category":"Sports","difficulty":"medium"},
    {"q":"In American football, how many points is a safety worth?","options":["1","2","3","4"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Which tennis player has won the most French Open titles?","options":["Roger Federer","Rafael Nadal","Novak Djokovic","Björn Borg"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Who was the first baseball player to hit 70 home runs in a single season?","options":["Barry Bonds","Mark McGwire","Sammy Sosa","Babe Ruth"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which driver has the most podium finishes in Formula One history?","options":["Michael Schumacher","Lewis Hamilton","Sebastian Vettel","Fernando Alonso"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"In what year did the NBA introduce the three-point line?","options":["1967","1979","1984","1991"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which boxer held the world heavyweight championship for the longest continuous period?","options":["Joe Louis","Muhammad Ali","Larry Holmes","Wladimir Klitschko"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"Which country has won the most Olympic gold medals in weightlifting?","options":["Russia","China","Bulgaria","United States"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"In which sport would you perform a 'front crawl'?","options":["Running","Swimming","Gymnastics","Wrestling"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"What is the maximum score possible in a single frame of bowling?","options":["100","200","300","400"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"Which of these is a type of golf club?","options":["Bat","Racket","Putter","Stick"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"In soccer, what is the term for when a player scores three goals in a single game?","options":["Triple","Hat-trick","Three-pointer","Treble"],"answer":1,"category":"Sports","difficulty":"easy"},
    {"q":"Which sport is played on a 'pitch'?","options":["Basketball","Tennis","Cricket","Golf"],"answer":2,"category":"Sports","difficulty":"easy"},
    {"q":"Which NFL team has appeared in the most Super Bowls?","options":["Pittsburgh Steelers","New England Patriots","Dallas Cowboys","Denver Broncos"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"In which year did Michael Jordan retire from the NBA for the final time?","options":["1998","2001","2003","2005"],"answer":2,"category":"Sports","difficulty":"medium"},
    {"q":"Which country hosted the 2016 Summer Olympics?","options":["China","Brazil","Russia","Japan"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"In baseball, what is the term for when a pitcher throws a complete game without allowing any hits?","options":["Perfect Game","No-Hitter","Shutout","Complete Game"],"answer":1,"category":"Sports","difficulty":"medium"},
    {"q":"Which tennis tournament is played on a grass surface?","options":["US Open","Australian Open","French Open","Wimbledon"],"answer":3,"category":"Sports","difficulty":"medium"},
    {"q":"Who is the only NHL player to score 200 points in a single season?","options":["Wayne Gretzky","Mario Lemieux","Phil Esposito","Bobby Orr"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"Which country has won the most Davis Cup titles in tennis?","options":["United States","Australia","France","Spain"],"answer":0,"category":"Sports","difficulty":"hard"},
    {"q":"In what year was the first modern Olympic Games held?","options":["1886","1896","1900","1904"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which boxer was known as 'The Brockton Blockbuster'?","options":["Joe Louis","Rocky Marciano","Jack Dempsey","Gene Tunney"],"answer":1,"category":"Sports","difficulty":"hard"},
    {"q":"Which NFL quarterback has thrown for the most touchdowns in a single season?","options":["Peyton Manning","Tom Brady","Patrick Mahomes","Drew Brees"],"answer":0,"category":"Sports","difficulty":"hard"}
]

