import os
import aiohttp
import asyncio
from datetime import datetime
from pyrogram import Client, filters, enums
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton, Message
from motor.motor_asyncio import AsyncIOMotorClient
from config import DB_URL, HF_API
from wallbot import wbot as app


mongo = AsyncIOMotorClient(DB_URL)
db = mongo.ai_image_bot

# =================== DATABASE HELPERS ===================

async def get_user(user_id: int):
    user = await db.users.find_one({"user_id": user_id})
    if not user:
        user = {"user_id": user_id, "images_generated": 0, "last_prompt": None, "joined_at": datetime.utcnow()}
        await db.users.insert_one(user)
    return user

async def update_user(user_id: int, prompt: str):
    await db.users.update_one(
        {"user_id": user_id},
        {"$inc": {"images_generated": 1}, "$set": {"last_prompt": prompt}},
        upsert=True
    )

async def get_leaderboard():
    cursor = db.users.find().sort("images_generated", -1).limit(10)
    return await cursor.to_list(length=10)

# =================== IMAGE GENERATION ===================

async def generate_image(prompt: str):
    url = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-2"
    headers = {"Authorization": f"Bearer {HF_API}"}
    payload = {"inputs": prompt}

    async with aiohttp.ClientSession() as session:
        async with session.post(url, headers=headers, json=payload) as resp:
            if resp.status != 200:
                text = await resp.text()
                raise Exception(f"API Error: {text}")
            return await resp.read()


@app.on_message(filters.command("imagine"))
async def imabwgine_cmd(_, message: Message):
    if len(message.command) < 2:
        return await message.reply("Usage: `/imagine <prompt>`", quote=True)

    prompt = message.text.split(maxsplit=1)[1].strip()
    user = await get_user(message.from_user.id)

    btn = InlineKeyboardMarkup([[InlineKeyboardButton("🔄 Generate Again", callback_data=f"regen_{message.from_user.id}_{prompt}")]])

    msg = await message.reply_text("🎨 Generating your image... please wait ⏳")

    try:
        image_data = await generate_image(prompt)
        await update_user(message.from_user.id, prompt)
        await msg.delete()
        await message.reply_photo(
            photo=image_data,
            caption=f"🖼 **Prompt:** `{prompt}`\n👤 Generated by {message.from_user.mention}",
            reply_markup=btn
        )
    except Exception as e:
        await msg.edit_text(f"❌ Failed to generate image.\nError: `{e}`")

@app.on_callback_query(filters.regex(r"^regen_(\d+)_(.+)$"))
async def rvbegen_image(_, query):
    user_id, prompt = query.data.split("_", 2)[1:]
    user_id = int(user_id)
    if query.from_user.id != user_id:
        return await query.answer("❌ Only the original user can regenerate this image!", show_alert=True)

    await query.answer("🎨 Regenerating...")
    try:
        image_data = await generate_image(prompt)
        await update_user(user_id, prompt)
        await query.message.reply_photo(
            photo=image_data,
            caption=f"🖼 **Prompt:** `{prompt}`\n🔁 Regenerated by {query.from_user.mention}",
        )
    except Exception as e:
        await query.message.reply(f"❌ Error while regenerating: `{e}`")

# =================== LEADERBOARD ===================

@app.on_callback_query(filters.regex("imleaderboard"))
async def show_leaderbsboard(_, query):
    users = await get_leaderboard()
    if not users:
        return await query.answer("No one has generated images yet!")

    text = "🏆 **Top AI Artists** 🏆\n\n"
    for i, user in enumerate(users, start=1):
        user_name = f"[User {user['user_id']}]"  # fallback
        count = user.get("images_generated", 0)
        text += f"**{i}.** {user_name} — 🖼 {count} images\n"

    await query.message.reply_text(text)
